### PR TITLE
KeyConfig Tooltips (Fixes #56)

### LINKED ISSUE #56: Tooltips for items and skills missing in keyconfig
**Repro steps:**
1. Bind skill to key config
1. Bind potion to key config
1. Hover over potion and skill

GMS v83:
image
image

HeavenMS 80e042:
image
image

### PR DESCRIPTION
**Pull request by SomeMushroom**
This adds tooltips for USE items and skills in the keyconfig. Fixes #56.

My client/server pair is currently having issues with monster spawns, but in tests the issue seems unrelated to these changes here. **We should test these on someone else's setup to confirm**.

This may need to be rebased once PR #71 is landed.

### CODE REVIEW

File: IO/UITypes/UIKeyConfig.cpp [hunk 1]
```diff
@@ -512,7 +512,7 @@ namespace ms
 		}
 	}
 
-	// UI
+	// UI: General
```
Comment (SomeMushroom) [inline IO/UITypes/UIKeyConfig.cpp]: Can modify the spaces to whatever we conclude in the other PR. Doesn't matter to me, this is just how I had it.

Comment (ryantpayton) [reply IO/UITypes/UIKeyConfig.cpp]: You were right 😁
